### ISSUE TITLE
Compiler inlines and optimizes the whole function to `return 330`

### ISSUE THREAD

**Issue by jhorstmann** [tailcallhq/rust-benchmarks#2]
Rust and its pattern matching is fast, but not that fast ;)

Rustc 1.77 seems to be able to optimize the whole `pattern_matching` function to the equivalent of `return 330`.

Rustc 1.78 seems to be able to do the same optimization also for the `dynamic_dispatch` version.

See https://rust.godbolt.org/z/zTrzhTbze for the assembly output.

A possible improvement to the benchmark could be to change `Action` to take a parameter, and to tunnel the parameter value through `criterion::black_box` to avoid compiler optimizations based on that value.

**Comment by tusharmath** [comment]
Thank @jhorstmann I have fixed the benchmark. Appreciate your help 🙏
